const { supabase, many, enrich } = require('../data');
const count = async (table, filters = {}) => {
  let query = supabase.from(table).select('*', { count: 'exact', head: true });
  Object.entries(filters).forEach(([key, value]) => { query = query.eq(key, value); });
  const { count: result, error } = await query;
  if (error) throw error;
  return result || 0;
};
const grouped = (rows, key) => Object.entries(rows.reduce((out, row) => { const value = row[key] || null; out[value] = (out[value] || 0) + 1; return out; }, {})).map(([id, total]) => ({ _id: id, count: total }));
exports.getDashboardStats = async (_req, res) => { try { const [totalUsers,totalClubs,totalEvents,totalPosts,totalJobs,totalAchievements,users,recentRows,pendingApprovals,pendingJobVerifications,reportedPosts] = await Promise.all([count('users'),count('clubs',{is_active:true}),count('events'),count('posts'),count('jobs'),count('achievements'),many(supabase.from('users').select('role,department')),many(supabase.from('events').select('*').order('created_at',{ascending:false}).limit(5)),count('events',{is_approved:false}),count('jobs',{is_verified:false}),count('posts',{is_reported:true})]); res.status(200).json({success:true,data:{totalUsers,totalClubs,totalEvents,totalPosts,totalJobs,totalAchievements,usersByRole:grouped(users,'role'),usersByDept:grouped(users,'department'),recentEvents:await Promise.all(recentRows.map(x=>enrich('events',x))),pendingApprovals,pendingJobVerifications,reportedPosts}}); } catch (err) { res.status(500).json({success:false,message:err.message}); } };
exports.getEngagementMetrics = async (_req,res) => { try { const since=new Date(Date.now()-30*86400000).toISOString(); const [newUsers,newEvents,newPosts,newAchievements,clubs]=await Promise.all(['users','events','posts','achievements'].map(t=>supabase.from(t).select('*',{count:'exact',head:true}).gte('created_at',since)).concat([many(supabase.from('clubs').select('*'))])); const topClubs=await Promise.all(clubs.map(async c=>({name:c.name,memberCount:await count('club_members',{club_id:c.id})}))); topClubs.sort((a,b)=>b.memberCount-a.memberCount);res.status(200).json({success:true,data:{newUsers:newUsers.count||0,newEvents:newEvents.count||0,newPosts:newPosts.count||0,newAchievements:newAchievements.count||0,topClubs:topClubs.slice(0,5)}}); }catch(err){res.status(500).json({success:false,message:err.message});} };
exports.getReportedContent=async(_q,r)=>{try{r.status(200).json({success:true,data:await Promise.all((await many(supabase.from('posts').select('*').eq('is_reported',true))).map(x=>enrich('posts',x)))});}catch(e){r.status(500).json({success:false,message:e.message});}};
exports.moderatePost=async(q,r)=>{try{if(q.body.action==='delete')await supabase.from('posts').delete().eq('id',q.params.id);else if(q.body.action==='dismiss')await supabase.from('posts').update({is_reported:false,reported_by:null}).eq('id',q.params.id);r.status(200).json({success:true,message:q.body.action==='delete'?'Post deleted':'Report dismissed'});}catch(e){r.status(500).json({success:false,message:e.message});}};
exports.approvePendingEvents=async(_q,r)=>{try{r.status(200).json({success:true,data:await Promise.all((await many(supabase.from('events').select('*').eq('is_approved',false))).map(x=>enrich('events',x)))});}catch(e){r.status(500).json({success:false,message:e.message});}};
exports.approvePendingJobs=async(_q,r)=>{try{r.status(200).json({success:true,data:await Promise.all((await many(supabase.from('jobs').select('*').eq('is_verified',false))).map(x=>enrich('jobs',x)))});}catch(e){r.status(500).json({success:false,message:e.message});}};
