const {supabase,one,maybeOne,many,page,range,enrich,notify}=require('../data');const asyncHandler=require('../utils/asyncHandler');const ApiError=require('../utils/ApiError');const {pick}=require('../utils/pick');
exports.createEvent=asyncHandler(async(req,res)=>{const d=pick(req.body,['title','description','date','location','club','targetAudience','department']);let approved=['admin','hod'].includes(req.user.role);if(!approved&&d.club){const c=await maybeOne(supabase.from('clubs').select('leader').eq('id',d.club));approved=c?.leader===req.user.id;}const e=await one(supabase.from('events').insert({...d,created_by:req.user.id,target_audience:d.targetAudience||'all',is_approved:approved,approved_by:approved?req.user.id:null}).select());res.status(201).json({success:true,data:await enrich('events',e,{detail:true})});});
exports.getEvents=asyncHandler(async(req,res)=>{const p=page(req.query.page,1),l=page(req.query.limit,20);let q=supabase.from('events').select('*',{count:'exact'}).eq('is_approved',true).order('date');if(req.query.department)q=q.eq('department',req.query.department);if(req.query.club)q=q.eq('club',req.query.club);if(req.query.upcoming==='true')q=q.gte('date',new Date().toISOString());const {data,error,count}=await q.range(...range(p,l));if(error)throw error;res.status(200).json({success:true,data:await Promise.all(data.map(e=>enrich('events',e))),total:count,pages:Math.ceil(count/l)});});
exports.getEvent=asyncHandler(async(req,res)=>{const e=await maybeOne(supabase.from('events').select('*').eq('id',req.params.id));if(!e)throw ApiError.notFound('Event not found');res.status(200).json({success:true,data:await enrich('events',e,{detail:true})});});
exports.updateEvent=asyncHandler(async(req,res)=>{const e=await maybeOne(supabase.from('events').select('*').eq('id',req.params.id));if(!e)throw ApiError.notFound('Event not found');if(e.created_by!==req.user.id&&req.user.role!=='admin')throw ApiError.forbidden();const d=pick(req.body,['title','description','date','location','targetAudience','department']);if(d.targetAudience){d.target_audience=d.targetAudience;delete d.targetAudience;}res.status(200).json({success:true,data:await enrich('events',await one(supabase.from('events').update(d).eq('id',e.id).select()))});});
exports.deleteEvent=asyncHandler(async(req,res)=>{const e=await maybeOne(supabase.from('events').select('*').eq('id',req.params.id));if(!e)throw ApiError.notFound('Event not found');if(e.created_by!==req.user.id&&req.user.role!=='admin')throw ApiError.forbidden();await supabase.from('events').delete().eq('id',e.id);res.status(200).json({success:true,message:'Event deleted'});});
exports.rsvpEvent=asyncHandler(async(req,res)=>{const e=await maybeOne(supabase.from('events').select('*').eq('id',req.params.id));if(!e)throw ApiError.notFound('Event not found');if(!e.is_approved)throw ApiError.badRequest('Event is not approved yet');if(await maybeOne(supabase.from('event_attendees').select('*').eq('event_id',e.id).eq('user_id',req.user.id)))throw ApiError.badRequest('Already RSVPed');await one(supabase.from('event_attendees').insert({event_id:e.id,user_id:req.user.id}).select());if(e.created_by!==req.user.id)await notify({user_id:e.created_by,title:'New RSVP',message:`${req.user.name} RSVPed to your event "${e.title}"`,type:'event',reference_id:e.id,reference_model:'Event'});res.status(200).json({success:true,message:'RSVPed',data:await enrich('events',e,{detail:true})});});
exports.cancelRsvp=asyncHandler(async(req,res)=>{const e=await maybeOne(supabase.from('events').select('*').eq('id',req.params.id));if(!e)throw ApiError.notFound('Event not found');await supabase.from('event_attendees').delete().eq('event_id',e.id).eq('user_id',req.user.id);res.status(200).json({success:true,message:'RSVP cancelled',data:await enrich('events',e,{detail:true})});});
exports.approveEvent=asyncHandler(async(req,res)=>{const e=await one(supabase.from('events').update({is_approved:true,approved_by:req.user.id}).eq('id',req.params.id).select());await notify({user_id:e.created_by,title:'Event Approved',message:`Your event "${e.title}" has been approved`,type:'event',reference_id:e.id,reference_model:'Event'});res.status(200).json({success:true,data:await enrich('events',e)});});exports.getPendingEvents=asyncHandler(async(_q,r)=>r.status(200).json({success:true,data:await Promise.all((await many(supabase.from('events').select('*').eq('is_approved',false))).map(x=>enrich('events',x)))}));exports.getEventAnalytics=asyncHandler(async(req,res)=>{const e=await maybeOne(supabase.from('events').select('*').eq('id',req.params.id));if(!e)throw ApiError.notFound('Event not found');const a=await many(supabase.from('event_attendees').select('user_id').eq('event_id',e.id));res.status(200).json({success:true,data:{rsvpCount:a.length,totalComments:0,date:e.date,location:e.location}});});
