-- Campus Connect initial Supabase schema. Apply with `supabase db push`.
create extension if not exists pgcrypto;

create type user_role as enum ('student', 'faculty', 'hod', 'admin', 'leader', 'sub_leader');
create type audience_type as enum ('club', 'department', 'all');
create type board_type as enum ('general', 'department', 'club', 'career', 'anonymous');
create type job_type as enum ('internship', 'job');
create type application_status as enum ('pending', 'accepted', 'rejected');
create type message_type as enum ('direct', 'group');

create table users (
  id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) <= 80),
  email text not null unique, password text not null, role user_role not null default 'student',
  department text, year smallint check (year between 1 and 5), skills jsonb not null default '[]', bio text check (char_length(bio) <= 500),
  profile_image text not null default 'https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y',
  privacy_settings jsonb not null default '{"profileVisible":true,"achievementsVisible":true}', is_active boolean not null default true,
  login_attempts integer not null default 0, lock_until timestamptz, last_login timestamptz, password_changed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table clubs (id uuid primary key default gen_random_uuid(), name text not null unique, description text, department text, leader uuid references users on delete set null, activities jsonb not null default '[]', achievements jsonb not null default '[]', logo text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table club_members (club_id uuid references clubs on delete cascade, user_id uuid references users on delete cascade, is_sub_leader boolean not null default false, created_at timestamptz not null default now(), primary key (club_id,user_id));
create table events (id uuid primary key default gen_random_uuid(), title text not null, description text, date timestamptz not null, location text, club uuid references clubs on delete set null, department text, created_by uuid references users on delete set null, target_audience audience_type not null default 'all', is_approved boolean not null default false, approved_by uuid references users on delete set null, reminders jsonb not null default '[]', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table event_attendees (event_id uuid references events on delete cascade, user_id uuid references users on delete cascade, primary key(event_id,user_id));
create table posts (id uuid primary key default gen_random_uuid(), title text not null check (char_length(title)<=200), content text not null, author uuid not null references users on delete cascade, club uuid references clubs on delete set null, department text, board_type board_type not null default 'general', media jsonb not null default '[]', is_pinned boolean not null default false, is_reported boolean not null default false, reported_by uuid references users on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table post_likes (post_id uuid references posts on delete cascade, user_id uuid references users on delete cascade, primary key(post_id,user_id));
create table post_comments (id uuid primary key default gen_random_uuid(), post_id uuid references posts on delete cascade, author uuid references users on delete cascade, content text not null, created_at timestamptz not null default now());
create table jobs (id uuid primary key default gen_random_uuid(), title text not null, description text not null, company text, domain text, location text, stipend text, deadline timestamptz, posted_by uuid references users on delete set null, department text, is_verified boolean not null default false, verified_by uuid references users on delete set null, type job_type not null default 'internship', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table job_applications (job_id uuid references jobs on delete cascade, user_id uuid references users on delete cascade, applied_at timestamptz not null default now(), status application_status not null default 'pending', primary key(job_id,user_id));
create table achievements (id uuid primary key default gen_random_uuid(), title text not null, description text, user_id uuid not null references users on delete cascade, club uuid references clubs on delete set null, department text, media jsonb not null default '[]', badge text, is_highlighted boolean not null default false, highlighted_by uuid references users on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table achievement_likes (achievement_id uuid references achievements on delete cascade, user_id uuid references users on delete cascade, primary key(achievement_id,user_id));
create table achievement_comments (id uuid primary key default gen_random_uuid(), achievement_id uuid references achievements on delete cascade, author uuid references users on delete set null, content text not null, created_at timestamptz not null default now());
create table messages (id uuid primary key default gen_random_uuid(), sender uuid not null references users on delete cascade, receiver uuid references users on delete cascade, club uuid references clubs on delete cascade, content text not null, is_read boolean not null default false, message_type message_type not null default 'direct', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check ((message_type='direct' and receiver is not null) or (message_type='group' and club is not null)));
create table notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references users on delete cascade, title text not null, message text not null, type text, reference_id uuid, reference_model text, is_read boolean not null default false, created_at timestamptz not null default now());
create index users_department_role_idx on users(department,role); create index events_date_approved_idx on events(date,is_approved); create index posts_created_idx on posts(is_pinned desc,created_at desc); create index jobs_deadline_verified_idx on jobs(deadline,is_verified); create index messages_direct_idx on messages(sender,receiver,created_at desc); create index notifications_user_idx on notifications(user_id,is_read,created_at desc);
-- This backend exclusively uses the service-role key. Do not expose it to clients.
alter table users enable row level security; alter table clubs enable row level security; alter table club_members enable row level security; alter table events enable row level security; alter table event_attendees enable row level security; alter table posts enable row level security; alter table post_likes enable row level security; alter table post_comments enable row level security; alter table jobs enable row level security; alter table job_applications enable row level security; alter table achievements enable row level security; alter table achievement_likes enable row level security; alter table achievement_comments enable row level security; alter table messages enable row level security; alter table notifications enable row level security;
